# Analysis


```{r setup, include=FALSE}
    library(FactoMineR)
    library(ggraph)
    library(here)
    library(igraph)
    library(kableExtra)
    library(tidygraph)
```


```{r}
     source(here("Functions", "bonacich.R"))
     source(here("Functions", "hits.R"))
     source(here("Functions", "salsa.R"))
     source(here("Functions", "seeley.R"))
```

```{r}
    set.seed(456)
    dg <- play_gnp(12, .25) %>% 
        mutate(name = LETTERS[1:12]) 
    A <- as.matrix(as_adjacency_matrix(dg))
    oz <- which(rowSums(A) == 0)
    iz <- which(colSums(A) == 0)
    iso.i <- which(degree(dg, mode = "in") == 0)
    iso.o <- which(degree(dg, mode = "out") == 0)
    v <- 1:12
    for (i in iso.i) {
        inei <- v[-c(iso.i)]
        dg <- add_edges(dg, c(sample(inei, 1),i))
        }
    for (i in iso.o) {
        onei <- v[-c(iso.o)]
        dg <- add_edges(dg, c(i,sample(onei,1)))
        }
    ug <- as.undirected(dg, mode = "collapse")
    A <- as.matrix(as_adjacency_matrix(dg))
    B <- as.matrix(as_adjacency_matrix(ug))
```

```{r}
    p <- ggraph(dg, layout = 'stress')
    p <- p + geom_edge_parallel(color = "steelblue4", edge_width = 1.15,
          arrow = arrow(length = unit(5, 'mm')),
          end_cap = circle(8, 'mm'), 
          sep = unit(8, 'mm'))
    p <- p + geom_node_point(aes(x = x, y = y), size = 22, color = "tan2") 
    p <- p + geom_node_text(aes(label = name), size = 12, color = "white")
    p <- p + theme_graph() 
    p
    ggplot2::ggsave(here("Plots", "directed.png"), width = 15, height = 15)
    
    p <- ggraph(ug, layout = 'stress')
    p <- p + geom_edge_link(color = "steelblue", edge_width = 1.25) 
    p <- p + geom_node_point(aes(x = x, y = y), size = 22, color = "tan2") 
    p <- p + geom_node_text(aes(label = name), size = 12, color = "white")
    p <- p + theme_graph() 
    p
    ggplot2::ggsave(here("Plots", "undirected.png"), width = 15, height = 15)
```

```{r}
     bon.res <- bonacich(B)
     seeley.res <- seeley(B)
     hits.res <- hits(A)
     t.b <- bon.res$m[, bon.res$k]
     t.b <- sort(t.b, decreasing = TRUE)
     t.b <- cbind(names(t.b), round(t.b, 3))
     t.s <- seeley.res$m[, seeley.res$k]
     t.s <- sort(t.s, decreasing = TRUE)
     t.s <- cbind(names(t.s), round(t.s, 3))
     t.a <- hits.res$m.a[, hits.res$k]
     t.h <- hits.res$m.h[, hits.res$k]
     t.a <- sort(t.a, decreasing = TRUE)
     t.h <- sort(t.h, decreasing = TRUE)
     t.a <- cbind(names(t.a), round(t.a, 3))
     t.h <- cbind(names(t.h), round(t.h, 3))
     t <- data.frame(cbind(t.b, t.s, t.a, t.h))
     t$X2 <- as.numeric(t$X2)
     t$X4 <- as.numeric(t$X4)
     t$X6 <- as.numeric(t$X6)
     t$X8 <- as.numeric(t$X8)

     kbl(t, format = "latex", booktabs = T, 
        linesep = "", digits = 3, align = "r",
        row.names = FALSE,
        col.names = c("", "Bonacich", "", "Seeley", "", 
                   "Hub Score", "", "Auth. Score")) %>%
        kable_styling(latex_options = c("hold_position")) %>% 
        column_spec(c(1, 3, 5, 7), bold = TRUE) %>% 
        column_spec(1:8, width = "1.75 em") %>% 
        row_spec(0, align = "l") %>% 
        save_kable(here("Tabs", "tab1.tex"))

```

```{r}
    source(here("Functions", "salsa.R"))
    source(here("Functions", "hits.R"))
    ca <- CA(A, graph = F)
    Dr <- diag(1/rowSums(A))
    Dc <- diag(1/colSums(A))
    sa <- salsa(A)
    ha <- hits(A)
    e1 <- eigen(Dr %*% A %*% t(Dc %*% A))
    e2 <- eigen(t(Dc %*% A) %*% Dr %*% A)
    e3 <- eigen(A %*% t(A))
    e4 <- eigen(t(A) %*% A)
    a <- cbind(Re(e1$vectors[, 1]), sa$m.h[, sa$k], 
               Re(e2$vectors[, 1]), sa$m.a[, sa$k], 
               ha$m.a[, ha$k], ha$m.h[, ha$k],
               ca$row$coord[,1], ca$col$coord[,1],
               Re(e3$vectors[, 1]), Re(e4$vectors[, 1]))
    round(cor(a), 2)
    round(a, 2)
```

          
          
          
          


